### ISSUE TITLE
PostHTML PostXML

### ISSUE THREAD

**Issue by voischev** [kisenka/postsvg#2]
https://github.com/posthtml/posthtml
https://github.com/postxml/postxml

;) 

maybe you join to posthtml project? ;)

**Comment by kisenka** [comment]
@voischev definitely yes. When I creating postsvg I don't know about posthtml. Can we discuss this in IM? Gitter, slack or something?

**Comment by voischev** [comment]
Find me in https://gitter.im/posthtml/posthtml 

DM https://gitter.im/voischev

**Comment by danielbayley** [comment]
I had the same idea [PostSVG and a few plugins for it], but if _PostHTML_ works seamlessly with SVG… @voischev does it?

**Comment by voischev** [comment]
PostHTML works with all XML like markup

**Comment by danielbayley** [comment]
Expect some plugins then :)
